#:schema https://raw.githubusercontent.com/martimlobao/starship/refs/heads/chore/python-binary-schema-context/.github/config-schema.json
# Change back to `https://starship.rs/config-schema.json` after merging https://github.com/starship/starship/pull/7415

add_newline = true

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "🪫 "

[directory]
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = "🌱 "

[nodejs]
symbol = "☕️"

[python]
python_binary = [
  ["uv", "run", "--no-python-downloads", "--no-project", "python"]
]

[username]
style_user = "bold dimmed blue"
show_always = false

[sudo]
disabled = false

[gcloud]
detect_env_vars = ["GCP"]

# Disable these modules, they're noisy
[aws]
disabled = true
