---
name: Lint PR
permissions:
  contents: read
  checks: write
  pull-requests: write
on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

jobs:
  trunk:
    name: Trunk Code Quality (PR)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
